import type { BenchmarkScore, CatalogModel } from "./types";

// ---------------------------------------------------------------------------
// Catalog — grounded in the LIVE NVIDIA NIM + OpenRouter model lists
// (route ids, context windows, pricing and modalities verified against the
// real /v1/models endpoints). Refreshed 2026-06-30.
//
// Invariants:
//   • license: "open" | "proprietary" reflects the actual weights.
//   • access:  "free"  = served on an OPERATOR key (every model with a NVIDIA
//              route, plus open-weight models OpenRouter serves cheaply).
//              "byok"  = closed frontier models routed through the user's own
//              OpenRouter key (or the operator key when OPERATOR_SERVE_PAID).
//   • Every route id below is a REAL provider model id.
//
// Benchmark scores are illustrative aggregates of public sources; each carries
// its own attribution + date. Keys: mmlu, gpqa, humaneval, swebench, math,
// aime, mmmu, arena (see benchmarks.ts).
// ---------------------------------------------------------------------------
const AA = "Artificial Analysis";
const AA_URL = "https://artificialanalysis.ai";
const ARENA = "LMSYS Chatbot Arena";
const ARENA_URL = "https://lmarena.ai/leaderboard";
const NV = "NVIDIA NIM";
const NV_URL = "https://build.nvidia.com";
const OR = "OpenRouter";
const OR_URL = "https://openrouter.ai/models";

function b(
  key: string,
  score: number,
  source: string,
  sourceUrl: string,
  measuredAt = "2026-06-01",
): BenchmarkScore {
  return { key, score, source, sourceUrl, measuredAt };
}

const ADDED = "2026-06-28";

export const MODELS: CatalogModel[] = [
  // ===== OpenAI ============================================================
  {
    id: "gpt-5-5",
    name: "GPT-5.5",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    trending: true,
    status: "ga",
    releaseDate: "2026-05-20",
    addedAt: ADDED,
    contextWindow: 1050000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 5, outputPerM: 30, cachedInputPerM: 0.5, effectiveFrom: "2026-05-20" },
    benchmarks: [
      b("gpqa", 92.5, OR, OR_URL),
      b("swebench", 82.0, OR, OR_URL),
      b("aime", 99.0, OR, OR_URL),
      b("arena", 1505, ARENA, ARENA_URL),
    ],
    latencyMs: 1200, throughputTps: 80, rating: 4.9,
    blurb: "OpenAI's frontier flagship — a 1M-context unified reasoning model topping coding and math.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5.5" }],
    tags: ["reasoning", "coding", "agentic"],
  },
  {
    id: "gpt-5-5-pro",
    name: "GPT-5.5 Pro",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2026-05-20",
    contextWindow: 1050000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 30, outputPerM: 180, effectiveFrom: "2026-05-20" },
    benchmarks: [
      b("gpqa", 93.8, OR, OR_URL),
      b("swebench", 84.5, OR, OR_URL),
      b("aime", 100, OR, OR_URL),
    ],
    latencyMs: 4200, throughputTps: 55, rating: 4.9,
    blurb: "Maximum-effort GPT-5.5 for the hardest research, math, and agentic coding.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5.5-pro" }],
    tags: ["reasoning", "math"],
  },
  {
    id: "gpt-5-4",
    name: "GPT-5.4",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2026-03-10",
    contextWindow: 1050000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 2.5, outputPerM: 15, cachedInputPerM: 0.25, effectiveFrom: "2026-03-10" },
    benchmarks: [
      b("gpqa", 90.0, OR, OR_URL),
      b("swebench", 79.0, OR, OR_URL),
      b("arena", 1480, ARENA, ARENA_URL),
    ],
    latencyMs: 1000, throughputTps: 90, rating: 4.8,
    blurb: "The cost-balanced 1M-context GPT-5 workhorse for production agents.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5.4" }],
    tags: ["reasoning", "coding"],
  },
  {
    id: "gpt-5-2",
    name: "GPT-5.2",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2026-01-22",
    contextWindow: 400000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.75, outputPerM: 14, cachedInputPerM: 0.175, effectiveFrom: "2026-01-22" },
    benchmarks: [
      b("gpqa", 88.0, OR, OR_URL),
      b("swebench", 76.0, OR, OR_URL),
      b("arena", 1460, ARENA, ARENA_URL),
    ],
    latencyMs: 1100, throughputTps: 85, rating: 4.8,
    blurb: "Strong reasoning generation with broad tool use and structured output.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5.2" }],
    tags: ["reasoning", "coding"],
  },
  {
    id: "gpt-5-1",
    name: "GPT-5.1",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-11-12",
    contextWindow: 400000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.25, outputPerM: 10, cachedInputPerM: 0.125, effectiveFrom: "2025-11-12" },
    benchmarks: [
      b("gpqa", 86.0, OR, OR_URL),
      b("aime", 96.0, OR, OR_URL),
      b("arena", 1445, ARENA, ARENA_URL),
    ],
    latencyMs: 1150, throughputTps: 82, rating: 4.7,
    blurb: "Adaptive-reasoning GPT-5 refresh with improved instruction following.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5.1" }],
    tags: ["reasoning"],
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-08-07",
    contextWindow: 400000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.25, outputPerM: 10, cachedInputPerM: 0.125, effectiveFrom: "2025-08-07" },
    benchmarks: [
      b("gpqa", 85.7, OR, OR_URL),
      b("swebench", 74.9, OR, OR_URL),
      b("aime", 94.6, OR, OR_URL),
      b("arena", 1430, ARENA, ARENA_URL),
    ],
    latencyMs: 1200, throughputTps: 80, rating: 4.7,
    blurb: "The model that unified the GPT and o-series — strong agentic coding and reasoning.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5" }],
    tags: ["reasoning", "coding", "agentic"],
  },
  {
    id: "gpt-5-codex",
    name: "GPT-5 Codex",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-09-15",
    contextWindow: 400000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.25, outputPerM: 10, cachedInputPerM: 0.125, effectiveFrom: "2025-09-15" },
    benchmarks: [
      b("swebench", 78.2, OR, OR_URL),
      b("humaneval", 96.0, AA, AA_URL),
    ],
    latencyMs: 1300, throughputTps: 78, rating: 4.8,
    blurb: "GPT-5 tuned for long-horizon agentic software engineering.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5-codex" }],
    tags: ["coding", "agentic"],
  },
  {
    id: "gpt-5-pro",
    name: "GPT-5 Pro",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-10-06",
    contextWindow: 400000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 15, outputPerM: 120, effectiveFrom: "2025-10-06" },
    benchmarks: [
      b("gpqa", 89.0, OR, OR_URL),
      b("aime", 98.0, OR, OR_URL),
    ],
    latencyMs: 5200, throughputTps: 50, rating: 4.8,
    blurb: "Extended-thinking GPT-5 for the hardest problems where accuracy beats cost.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5-pro" }],
    tags: ["reasoning", "math"],
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 mini",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-08-07",
    contextWindow: 400000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.25, outputPerM: 2, cachedInputPerM: 0.025, effectiveFrom: "2025-08-07" },
    benchmarks: [
      b("gpqa", 78.0, OR, OR_URL),
      b("aime", 91.0, OR, OR_URL),
      b("arena", 1380, ARENA, ARENA_URL),
    ],
    latencyMs: 620, throughputTps: 120, rating: 4.6,
    blurb: "Cost-efficient GPT-5 — most of the quality, a fraction of the price.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5-mini" }],
    tags: ["reasoning", "cheap", "fast"],
  },
  {
    id: "gpt-5-nano",
    name: "GPT-5 nano",
    provider: "OpenAI",
    family: "GPT-5",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-08-07",
    contextWindow: 400000,
    maxOutput: 128000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.05, outputPerM: 0.4, cachedInputPerM: 0.005, effectiveFrom: "2025-08-07" },
    benchmarks: [b("aime", 85.0, OR, OR_URL), b("mmlu", 84.0, AA, AA_URL)],
    latencyMs: 320, throughputTps: 180, rating: 4.3,
    blurb: "The cheapest, fastest GPT-5 — high-volume classification and extraction.",
    routes: [{ provider: "openrouter", model: "openai/gpt-5-nano" }],
    tags: ["cheap", "fast"],
  },
  {
    id: "gpt-4-1",
    name: "GPT-4.1",
    provider: "OpenAI",
    family: "GPT-4.1",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-04-14",
    contextWindow: 1047576,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: true },
    pricing: { inputPerM: 2, outputPerM: 8, cachedInputPerM: 0.5, effectiveFrom: "2025-04-14" },
    benchmarks: [
      b("gpqa", 66.3, AA, AA_URL),
      b("swebench", 54.6, AA, AA_URL),
      b("arena", 1330, ARENA, ARENA_URL),
    ],
    latencyMs: 480, throughputTps: 100, rating: 4.5,
    blurb: "1M-context non-reasoning model tuned for coding and instruction following.",
    routes: [{ provider: "openrouter", model: "openai/gpt-4.1" }],
    tags: ["coding", "long-context"],
  },
  {
    id: "gpt-4-1-mini",
    name: "GPT-4.1 mini",
    provider: "OpenAI",
    family: "GPT-4.1",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-04-14",
    contextWindow: 1047576,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: true },
    pricing: { inputPerM: 0.4, outputPerM: 1.6, cachedInputPerM: 0.1, effectiveFrom: "2025-04-14" },
    benchmarks: [b("gpqa", 57.0, AA, AA_URL), b("arena", 1300, ARENA, ARENA_URL)],
    latencyMs: 380, throughputTps: 130, rating: 4.3,
    blurb: "Small, fast 1M-context model — a strong cheap default for high volume.",
    routes: [{ provider: "openrouter", model: "openai/gpt-4.1-mini" }],
    tags: ["cheap", "fast", "long-context"],
  },
  {
    id: "gpt-4-1-nano",
    name: "GPT-4.1 nano",
    provider: "OpenAI",
    family: "GPT-4.1",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-04-14",
    contextWindow: 1047576,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: true },
    pricing: { inputPerM: 0.1, outputPerM: 0.4, cachedInputPerM: 0.025, effectiveFrom: "2025-04-14" },
    benchmarks: [b("mmlu", 80.1, AA, AA_URL)],
    latencyMs: 300, throughputTps: 160, rating: 4.1,
    blurb: "The cheapest GPT-4.1 — lightweight extraction and routing at scale.",
    routes: [{ provider: "openrouter", model: "openai/gpt-4.1-nano" }],
    tags: ["cheap", "fast"],
  },
  {
    id: "o3",
    name: "o3",
    provider: "OpenAI",
    family: "o-series",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-04-16",
    contextWindow: 200000,
    maxOutput: 100000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 2, outputPerM: 8, cachedInputPerM: 0.5, effectiveFrom: "2025-06-10" },
    benchmarks: [
      b("gpqa", 83.3, AA, AA_URL),
      b("aime", 91.6, AA, AA_URL),
      b("swebench", 69.1, AA, AA_URL),
      b("arena", 1385, ARENA, ARENA_URL),
    ],
    latencyMs: 8200, throughputTps: 80, rating: 4.7,
    blurb: "Deliberate reasoning model with tool use inside the chain of thought.",
    routes: [{ provider: "openrouter", model: "openai/o3" }],
    tags: ["reasoning", "math", "agentic"],
  },
  {
    id: "o3-pro",
    name: "o3-pro",
    provider: "OpenAI",
    family: "o-series",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-06-10",
    contextWindow: 200000,
    maxOutput: 100000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 20, outputPerM: 80, effectiveFrom: "2025-06-10" },
    benchmarks: [b("gpqa", 85.0, AA, AA_URL), b("aime", 93.0, AA, AA_URL)],
    latencyMs: 12000, throughputTps: 45, rating: 4.7,
    blurb: "Maximum-compute o3 for the hardest scientific and mathematical problems.",
    routes: [{ provider: "openrouter", model: "openai/o3-pro" }],
    tags: ["reasoning", "math"],
  },
  {
    id: "o4-mini",
    name: "o4-mini",
    provider: "OpenAI",
    family: "o-series",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-04-16",
    contextWindow: 200000,
    maxOutput: 100000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.1, outputPerM: 4.4, cachedInputPerM: 0.275, effectiveFrom: "2025-04-16" },
    benchmarks: [
      b("gpqa", 81.4, AA, AA_URL),
      b("aime", 93.4, AA, AA_URL),
      b("arena", 1355, ARENA, ARENA_URL),
    ],
    latencyMs: 5600, throughputTps: 110, rating: 4.6,
    blurb: "Fast, cheap reasoning model that tops AIME — superb STEM value.",
    routes: [{ provider: "openrouter", model: "openai/o4-mini" }],
    tags: ["reasoning", "math", "cheap"],
  },
  {
    id: "gpt-oss-120b",
    name: "GPT-OSS 120B",
    provider: "OpenAI",
    family: "GPT-OSS",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2025-08-05",
    addedAt: ADDED,
    contextWindow: 131072,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.03, outputPerM: 0.15, effectiveFrom: "2025-08-05" },
    benchmarks: [
      b("gpqa", 72.0, OR, OR_URL),
      b("aime", 88.0, OR, OR_URL),
      b("arena", 1330, ARENA, ARENA_URL),
    ],
    latencyMs: 600, throughputTps: 140, rating: 4.6,
    blurb: "OpenAI's open-weight (Apache-2.0) reasoning model — frontier-adjacent, self-hostable.",
    routes: [
      { provider: "groq", model: "openai/gpt-oss-120b" },
      { provider: "nvidia", model: "openai/gpt-oss-120b" },
      { provider: "openrouter", model: "openai/gpt-oss-120b" },
      { provider: "local", model: "gpt-oss:120b" },
    ],
    tags: ["open", "reasoning", "self-host"],
  },
  {
    id: "gpt-oss-20b",
    name: "GPT-OSS 20B",
    provider: "OpenAI",
    family: "GPT-OSS",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-08-05",
    contextWindow: 131072,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.029, outputPerM: 0.14, effectiveFrom: "2025-08-05" },
    benchmarks: [b("gpqa", 62.0, OR, OR_URL), b("aime", 80.0, OR, OR_URL)],
    latencyMs: 300, throughputTps: 190, rating: 4.3,
    blurb: "Compact open-weight reasoning model that runs on a single GPU.",
    routes: [
      { provider: "groq", model: "openai/gpt-oss-20b" },
      { provider: "nvidia", model: "openai/gpt-oss-20b" },
      { provider: "openrouter", model: "openai/gpt-oss-20b" },
      { provider: "local", model: "gpt-oss:20b" },
    ],
    tags: ["open", "reasoning", "cheap", "self-host"],
  },

  // ===== Anthropic =========================================================
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    trending: true,
    status: "ga",
    releaseDate: "2026-05-05",
    addedAt: ADDED,
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 5, outputPerM: 25, cachedInputPerM: 0.5, effectiveFrom: "2026-05-05" },
    benchmarks: [
      b("gpqa", 91.0, OR, OR_URL),
      b("swebench", 85.0, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1500, ARENA, ARENA_URL),
    ],
    latencyMs: 1100, throughputTps: 70, rating: 4.9,
    blurb: "Anthropic's most capable model — best-in-class agentic coding with a 1M context.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-opus-4.8" }],
    tags: ["reasoning", "coding", "agentic"],
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2026-02-18",
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 5, outputPerM: 25, cachedInputPerM: 0.5, effectiveFrom: "2026-02-18" },
    benchmarks: [
      b("gpqa", 89.0, OR, OR_URL),
      b("swebench", 83.0, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1488, ARENA, ARENA_URL),
    ],
    latencyMs: 1080, throughputTps: 72, rating: 4.9,
    blurb: "Frontier reasoning + coding with extended thinking and a 1M context.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-opus-4.7" }],
    tags: ["reasoning", "coding"],
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-12-10",
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 5, outputPerM: 25, cachedInputPerM: 0.5, effectiveFrom: "2025-12-10" },
    benchmarks: [
      b("gpqa", 87.5, OR, OR_URL),
      b("swebench", 81.0, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1472, ARENA, ARENA_URL),
    ],
    latencyMs: 1080, throughputTps: 72, rating: 4.8,
    blurb: "1M-context Opus with strong agentic tool use.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-opus-4.6" }],
    tags: ["reasoning", "coding"],
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-11-24",
    contextWindow: 200000,
    maxOutput: 64000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 5, outputPerM: 25, cachedInputPerM: 0.5, effectiveFrom: "2025-11-24" },
    benchmarks: [
      b("gpqa", 86.0, OR, OR_URL),
      b("swebench", 80.9, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1460, ARENA, ARENA_URL),
    ],
    latencyMs: 1050, throughputTps: 70, rating: 4.8,
    blurb: "The Opus that brought frontier quality to a lower price point.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-opus-4.5" }],
    tags: ["reasoning", "coding"],
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    trending: true,
    status: "ga",
    releaseDate: "2026-04-02",
    addedAt: ADDED,
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 3, outputPerM: 15, cachedInputPerM: 0.3, effectiveFrom: "2026-04-02" },
    benchmarks: [
      b("gpqa", 84.0, OR, OR_URL),
      b("swebench", 80.0, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1450, ARENA, ARENA_URL),
    ],
    latencyMs: 720, throughputTps: 90, rating: 4.8,
    blurb: "The best coding/agent workhorse — frontier quality at Sonnet pricing, 1M context.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-sonnet-4.6" }],
    tags: ["coding", "agentic", "long-context"],
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-09-29",
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 3, outputPerM: 15, cachedInputPerM: 0.3, effectiveFrom: "2025-09-29" },
    benchmarks: [
      b("gpqa", 83.0, OR, OR_URL),
      b("swebench", 77.2, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1430, ARENA, ARENA_URL),
    ],
    latencyMs: 740, throughputTps: 88, rating: 4.7,
    blurb: "Frontier coding/agent quality at Sonnet pricing with a 1M context.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-sonnet-4.5" }],
    tags: ["coding", "agentic", "long-context"],
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-05-22",
    contextWindow: 1000000,
    maxOutput: 64000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 3, outputPerM: 15, cachedInputPerM: 0.3, effectiveFrom: "2025-05-22" },
    benchmarks: [
      b("gpqa", 75.4, AA, AA_URL),
      b("swebench", 72.7, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1340, ARENA, ARENA_URL),
    ],
    latencyMs: 720, throughputTps: 86, rating: 4.7,
    blurb: "The original Claude 4 balanced model with optional extended thinking.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-sonnet-4" }],
    tags: ["coding", "long-context"],
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    family: "Claude 4",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-10-15",
    contextWindow: 200000,
    maxOutput: 32000,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1, outputPerM: 5, cachedInputPerM: 0.1, effectiveFrom: "2025-10-15" },
    benchmarks: [
      b("gpqa", 65.0, AA, AA_URL),
      b("swebench", 73.3, "Anthropic", "https://www.anthropic.com"),
      b("arena", 1310, ARENA, ARENA_URL),
    ],
    latencyMs: 420, throughputTps: 130, rating: 4.5,
    blurb: "Near-frontier coding at a fraction of the cost and latency.",
    routes: [{ provider: "openrouter", model: "anthropic/claude-haiku-4.5" }],
    tags: ["fast", "coding", "cheap"],
  },

  // ===== Google (Gemini closed; Gemma open) ================================
  {
    id: "gemini-3-1-pro",
    name: "Gemini 3.1 Pro",
    provider: "Google",
    family: "Gemini 3",
    license: "proprietary",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2026-04-10",
    addedAt: ADDED,
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 2, outputPerM: 12, cachedInputPerM: 0.5, effectiveFrom: "2026-04-10" },
    benchmarks: [
      b("gpqa", 90.0, OR, OR_URL),
      b("aime", 95.0, "Google", "https://deepmind.google"),
      b("mmmu", 84.0, OR, OR_URL),
      b("arena", 1495, ARENA, ARENA_URL),
    ],
    latencyMs: 900, throughputTps: 100, rating: 4.9,
    blurb: "Google's thinking flagship — top of the Arena, 1M multimodal context.",
    routes: [
      { provider: "google", model: "gemini-3.1-pro-preview" },
      { provider: "openrouter", model: "google/gemini-3.1-pro-preview" },
    ],
    tags: ["reasoning", "long-context", "multimodal"],
  },
  {
    id: "gemini-3-5-flash",
    name: "Gemini 3.5 Flash",
    provider: "Google",
    family: "Gemini 3",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2026-05-28",
    addedAt: ADDED,
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.5, outputPerM: 9, cachedInputPerM: 0.375, effectiveFrom: "2026-05-28" },
    benchmarks: [
      b("gpqa", 84.0, OR, OR_URL),
      b("aime", 90.0, "Google", "https://deepmind.google"),
      b("arena", 1460, ARENA, ARENA_URL),
    ],
    latencyMs: 380, throughputTps: 175, rating: 4.7,
    blurb: "Fast 1M-context thinking model with excellent price-performance.",
    routes: [
      { provider: "google", model: "gemini-3.5-flash" },
      { provider: "openrouter", model: "google/gemini-3.5-flash" },
    ],
    tags: ["fast", "long-context", "multimodal"],
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    provider: "Google",
    family: "Gemini 3",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2026-01-15",
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.5, outputPerM: 3, cachedInputPerM: 0.125, effectiveFrom: "2026-01-15" },
    benchmarks: [b("gpqa", 80.0, OR, OR_URL), b("arena", 1430, ARENA, ARENA_URL)],
    latencyMs: 360, throughputTps: 180, rating: 4.6,
    blurb: "First-gen Gemini 3 Flash — cheap, fast multimodal reasoning.",
    routes: [
      { provider: "google", model: "gemini-3-flash-preview" },
      { provider: "openrouter", model: "google/gemini-3-flash-preview" },
    ],
    tags: ["fast", "multimodal", "cheap"],
  },
  {
    id: "gemini-3-1-flash-lite",
    name: "Gemini 3.1 Flash Lite",
    provider: "Google",
    family: "Gemini 3",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2026-05-12",
    addedAt: ADDED,
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: true },
    pricing: { inputPerM: 0.1, outputPerM: 0.4, cachedInputPerM: 0.025, effectiveFrom: "2026-05-12" },
    benchmarks: [b("mmlu", 84.0, "Google", "https://deepmind.google")],
    latencyMs: 280, throughputTps: 210, rating: 4.4,
    blurb: "The cheapest Gemini 3 — 1M context for high-volume multimodal workloads.",
    routes: [{ provider: "google", model: "gemini-3.1-flash-lite" }],
    tags: ["cheap", "fast", "long-context"],
  },
  {
    id: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    family: "Gemini 2.5",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2025-06-17",
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.25, outputPerM: 10, cachedInputPerM: 0.31, effectiveFrom: "2025-06-17" },
    benchmarks: [
      b("gpqa", 84.0, AA, AA_URL),
      b("swebench", 63.8, "Google", "https://deepmind.google"),
      b("mmmu", 82.0, AA, AA_URL),
      b("arena", 1440, ARENA, ARENA_URL),
    ],
    latencyMs: 900, throughputTps: 95, rating: 4.8,
    blurb: "The thinking model that topped the Arena in 2025; 1M multimodal context.",
    routes: [
      { provider: "google", model: "gemini-2.5-pro" },
      { provider: "openrouter", model: "google/gemini-2.5-pro" },
    ],
    tags: ["reasoning", "long-context", "multimodal"],
  },
  {
    id: "gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    family: "Gemini 2.5",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2025-06-17",
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.3, outputPerM: 2.5, cachedInputPerM: 0.075, effectiveFrom: "2025-06-17" },
    benchmarks: [b("gpqa", 78.3, AA, AA_URL), b("arena", 1390, ARENA, ARENA_URL)],
    latencyMs: 360, throughputTps: 170, rating: 4.6,
    blurb: "Fast 1M-context thinking model with strong price-performance.",
    routes: [
      { provider: "google", model: "gemini-2.5-flash" },
      { provider: "openrouter", model: "google/gemini-2.5-flash" },
    ],
    tags: ["fast", "long-context", "multimodal"],
  },
  {
    id: "gemini-2-5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    provider: "Google",
    family: "Gemini 2.5",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2025-07-22",
    contextWindow: 1048576,
    maxOutput: 65536,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: true },
    pricing: { inputPerM: 0.1, outputPerM: 0.4, cachedInputPerM: 0.025, effectiveFrom: "2025-07-22" },
    benchmarks: [b("mmlu", 82.0, AA, AA_URL)],
    latencyMs: 300, throughputTps: 200, rating: 4.3,
    blurb: "The cheapest 1M-context Gemini — high-volume multimodal workloads.",
    routes: [
      { provider: "google", model: "gemini-2.5-flash-lite" },
      { provider: "openrouter", model: "google/gemini-2.5-flash-lite" },
    ],
    tags: ["cheap", "fast", "long-context"],
  },
  {
    id: "gemma-4-31b",
    name: "Gemma 4 31B",
    provider: "Google",
    family: "Gemma 4",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2026-03-04",
    addedAt: ADDED,
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.1, outputPerM: 0.2, effectiveFrom: "2026-03-04" },
    benchmarks: [b("gpqa", 50.0, NV, NV_URL), b("mmlu", 82.0, NV, NV_URL), b("arena", 1370, ARENA, ARENA_URL)],
    latencyMs: 360, throughputTps: 110, rating: 4.4,
    blurb: "Google's latest open multimodal model — Arena-leading among open weights.",
    routes: [
      { provider: "nvidia", model: "google/gemma-4-31b-it" },
      { provider: "google", model: "gemma-4-31b-it" },
      { provider: "local", model: "gemma4:31b" },
    ],
    tags: ["open", "multimodal", "multilingual"],
  },
  {
    id: "gemma-4-26b",
    name: "Gemma 4 26B A4B",
    provider: "Google",
    family: "Gemma 4",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2026-03-04",
    addedAt: ADDED,
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.05, outputPerM: 0.1, effectiveFrom: "2026-03-04" },
    benchmarks: [b("mmlu", 79.0, "Google", "https://deepmind.google")],
    latencyMs: 280, throughputTps: 160, rating: 4.2,
    blurb: "Sparse-MoE Gemma 4 — 26B total, ~4B active for fast, cheap open inference.",
    routes: [{ provider: "google", model: "gemma-4-26b-a4b-it" }],
    tags: ["open", "cheap", "fast"],
  },
  {
    id: "gemma-3-27b",
    name: "Gemma 3 27B",
    provider: "Google",
    family: "Gemma 3",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-03-12",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.08, outputPerM: 0.16, effectiveFrom: "2025-03-12" },
    benchmarks: [b("mmlu", 78.6, AA, AA_URL), b("arena", 1340, ARENA, ARENA_URL)],
    latencyMs: 360, throughputTps: 110, rating: 4.3,
    blurb: "Multimodal, multilingual open model — a strong self-host default.",
    routes: [
      { provider: "openrouter", model: "google/gemma-3-27b-it" },
      { provider: "local", model: "gemma3:27b" },
    ],
    tags: ["open", "multimodal"],
  },
  {
    id: "gemma-3-12b",
    name: "Gemma 3 12B",
    provider: "Google",
    family: "Gemma 3",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-03-12",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.05, outputPerM: 0.15, effectiveFrom: "2025-03-12" },
    benchmarks: [b("mmlu", 74.5, AA, AA_URL)],
    latencyMs: 300, throughputTps: 140, rating: 4.1,
    blurb: "Mid-size Gemma 3 with vision and a long context.",
    routes: [
      { provider: "nvidia", model: "google/gemma-3-12b-it" },
      { provider: "openrouter", model: "google/gemma-3-12b-it" },
      { provider: "local", model: "gemma3:12b" },
    ],
    tags: ["open", "multimodal", "cheap"],
  },

  // ===== xAI ===============================================================
  {
    id: "grok-4-3",
    name: "Grok 4.3",
    provider: "xAI",
    family: "Grok",
    license: "proprietary",
    access: "byok",
    trending: true,
    status: "ga",
    releaseDate: "2026-05-15",
    addedAt: ADDED,
    contextWindow: 1000000,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.25, outputPerM: 2.5, cachedInputPerM: 0.31, effectiveFrom: "2026-05-15" },
    benchmarks: [
      b("gpqa", 89.0, OR, OR_URL),
      b("aime", 97.0, "xAI", "https://x.ai"),
      b("arena", 1480, ARENA, ARENA_URL),
    ],
    latencyMs: 1100, throughputTps: 85, rating: 4.8,
    blurb: "xAI's reasoning flagship with real-time knowledge and native tool use.",
    routes: [{ provider: "openrouter", model: "x-ai/grok-4.3" }],
    tags: ["reasoning", "realtime", "agentic"],
  },
  {
    id: "grok-4-20",
    name: "Grok 4.20",
    provider: "xAI",
    family: "Grok",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2026-04-20",
    contextWindow: 2000000,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.25, outputPerM: 2.5, cachedInputPerM: 0.31, effectiveFrom: "2026-04-20" },
    benchmarks: [b("gpqa", 87.5, OR, OR_URL), b("arena", 1470, ARENA, ARENA_URL)],
    latencyMs: 1200, throughputTps: 80, rating: 4.7,
    blurb: "2M-context Grok with multi-agent tooling and live search.",
    routes: [{ provider: "openrouter", model: "x-ai/grok-4.20" }],
    tags: ["reasoning", "realtime", "long-context"],
  },

  // ===== Meta — Llama (open) ===============================================
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    provider: "Meta",
    family: "Llama 4",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2025-04-05",
    contextWindow: 1048576,
    maxOutput: 16384,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.15, outputPerM: 0.6, effectiveFrom: "2025-04-05" },
    benchmarks: [
      b("gpqa", 69.8, "Meta", "https://ai.meta.com"),
      b("mmmu", 73.4, "Meta", "https://ai.meta.com"),
      b("arena", 1370, ARENA, ARENA_URL),
    ],
    latencyMs: 540, throughputTps: 120, rating: 4.6,
    blurb: "Meta's 400B MoE flagship — natively multimodal, 1M context, open weights.",
    routes: [
      { provider: "nvidia", model: "meta/llama-4-maverick-17b-128e-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-4-maverick" },
      { provider: "local", model: "llama4:maverick" },
    ],
    tags: ["open", "moe", "multimodal", "long-context"],
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    provider: "Meta",
    family: "Llama 4",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-04-05",
    contextWindow: 10000000,
    maxOutput: 16384,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.1, outputPerM: 0.3, effectiveFrom: "2025-04-05" },
    benchmarks: [b("gpqa", 57.2, "Meta", "https://ai.meta.com"), b("arena", 1320, ARENA, ARENA_URL)],
    latencyMs: 420, throughputTps: 140, rating: 4.4,
    blurb: "Efficient MoE with a 10M-token context — fits on a single GPU.",
    routes: [
      { provider: "groq", model: "meta-llama/llama-4-scout-17b-16e-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-4-scout" },
      { provider: "local", model: "llama4:scout" },
    ],
    tags: ["open", "moe", "long-context", "cheap"],
  },
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    family: "Llama 3.3",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-12-06",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.1, outputPerM: 0.32, effectiveFrom: "2024-12-06" },
    benchmarks: [b("humaneval", 88.4, AA, AA_URL), b("mmlu", 86.0, AA, AA_URL), b("arena", 1257, ARENA, ARENA_URL)],
    latencyMs: 510, throughputTps: 92, rating: 4.4,
    blurb: "70B that rivals 405B quality — the sweet spot for affordable open self-hosting.",
    routes: [
      { provider: "groq", model: "llama-3.3-70b-versatile" },
      { provider: "nvidia", model: "meta/llama-3.3-70b-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-3.3-70b-instruct" },
      { provider: "local", model: "llama3.3" },
    ],
    tags: ["open", "value"],
  },
  {
    id: "llama-3-1-70b",
    name: "Llama 3.1 70B",
    provider: "Meta",
    family: "Llama 3.1",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-07-23",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.4, outputPerM: 0.4, effectiveFrom: "2024-09-01" },
    benchmarks: [b("mmlu", 83.6, AA, AA_URL), b("arena", 1248, ARENA, ARENA_URL)],
    latencyMs: 480, throughputTps: 95, rating: 4.2,
    blurb: "The dependable 70B workhorse and fine-tuning base.",
    routes: [
      { provider: "nvidia", model: "meta/llama-3.1-70b-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-3.1-70b-instruct" },
      { provider: "local", model: "llama3.1:70b" },
    ],
    tags: ["open", "value"],
  },
  {
    id: "llama-3-1-8b",
    name: "Llama 3.1 8B",
    provider: "Meta",
    family: "Llama 3.1",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-07-23",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.02, outputPerM: 0.03, effectiveFrom: "2024-09-01" },
    benchmarks: [b("mmlu", 73.0, AA, AA_URL), b("arena", 1176, ARENA, ARENA_URL)],
    latencyMs: 220, throughputTps: 180, rating: 3.9,
    blurb: "Tiny, fast, nearly-free open model for high-throughput pipelines.",
    routes: [
      { provider: "groq", model: "llama-3.1-8b-instant" },
      { provider: "nvidia", model: "meta/llama-3.1-8b-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-3.1-8b-instruct" },
      { provider: "local", model: "llama3.1:8b" },
    ],
    tags: ["cheap", "fast", "open"],
  },
  {
    id: "llama-3-2-90b-vision",
    name: "Llama 3.2 90B Vision",
    provider: "Meta",
    family: "Llama 3.2",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-09-25",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.35, outputPerM: 0.35, effectiveFrom: "2024-09-25" },
    benchmarks: [b("mmmu", 60.3, "Meta", "https://ai.meta.com"), b("mmlu", 86.0, AA, AA_URL)],
    latencyMs: 620, throughputTps: 70, rating: 4.2,
    blurb: "Meta's largest open vision-language model — self-hostable document understanding.",
    routes: [
      { provider: "nvidia", model: "meta/llama-3.2-90b-vision-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-3.2-90b-vision-instruct" },
      { provider: "local", model: "llama3.2-vision:90b" },
    ],
    tags: ["open", "vision"],
  },
  {
    id: "llama-3-2-11b-vision",
    name: "Llama 3.2 11B Vision",
    provider: "Meta",
    family: "Llama 3.2",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-09-25",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.345, outputPerM: 0.345, effectiveFrom: "2024-09-25" },
    benchmarks: [b("mmmu", 50.7, "Meta", "https://ai.meta.com")],
    latencyMs: 320, throughputTps: 130, rating: 4.0,
    blurb: "Compact open vision model — cheap multimodal understanding at the edge.",
    routes: [
      { provider: "nvidia", model: "meta/llama-3.2-11b-vision-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-3.2-11b-vision-instruct" },
      { provider: "local", model: "llama3.2-vision:11b" },
    ],
    tags: ["open", "vision", "cheap"],
  },
  {
    id: "llama-3-2-3b",
    name: "Llama 3.2 3B",
    provider: "Meta",
    family: "Llama 3.2",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-09-25",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.051, outputPerM: 0.335, effectiveFrom: "2024-09-25" },
    benchmarks: [b("mmlu", 63.4, AA, AA_URL)],
    latencyMs: 160, throughputTps: 220, rating: 3.7,
    blurb: "Tiny edge model for on-device assistants and classification.",
    routes: [
      { provider: "nvidia", model: "meta/llama-3.2-3b-instruct" },
      { provider: "openrouter", model: "meta-llama/llama-3.2-3b-instruct" },
      { provider: "local", model: "llama3.2:3b" },
    ],
    tags: ["open", "cheap", "edge"],
  },

  // ===== DeepSeek (open) ===================================================
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    family: "DeepSeek V4",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2026-04-25",
    addedAt: ADDED,
    contextWindow: 1048576,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.435, outputPerM: 0.87, cachedInputPerM: 0.11, effectiveFrom: "2026-04-25" },
    benchmarks: [
      b("gpqa", 84.0, OR, OR_URL),
      b("swebench", 74.0, "DeepSeek", "https://deepseek.com"),
      b("aime", 95.0, "DeepSeek", "https://deepseek.com"),
      b("arena", 1455, ARENA, ARENA_URL),
    ],
    latencyMs: 760, throughputTps: 70, rating: 4.8,
    blurb: "DeepSeek's frontier open MoE — 1M context, hybrid thinking, astonishing value.",
    routes: [
      { provider: "openrouter", model: "deepseek/deepseek-v4-pro" },
      { provider: "nvidia", model: "deepseek-ai/deepseek-v4-pro" },
      { provider: "local", model: "deepseek-v4" },
    ],
    tags: ["open", "moe", "reasoning", "value"],
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "DeepSeek",
    family: "DeepSeek V4",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2026-04-25",
    contextWindow: 1048576,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.09, outputPerM: 0.18, effectiveFrom: "2026-04-25" },
    benchmarks: [b("gpqa", 76.0, OR, OR_URL), b("aime", 88.0, "DeepSeek", "https://deepseek.com")],
    latencyMs: 420, throughputTps: 140, rating: 4.5,
    blurb: "Fast, cheap V4 variant with a 1M context — strong open value.",
    routes: [
      { provider: "openrouter", model: "deepseek/deepseek-v4-flash" },
      { provider: "nvidia", model: "deepseek-ai/deepseek-v4-flash" },
      { provider: "local", model: "deepseek-v4-flash" },
    ],
    tags: ["open", "reasoning", "cheap"],
  },
  {
    id: "deepseek-v3-2",
    name: "DeepSeek V3.2",
    provider: "DeepSeek",
    family: "DeepSeek V3",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-12-01",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.229, outputPerM: 0.343, cachedInputPerM: 0.057, effectiveFrom: "2025-12-01" },
    benchmarks: [b("gpqa", 79.0, OR, OR_URL), b("swebench", 68.0, "DeepSeek", "https://deepseek.com"), b("arena", 1400, ARENA, ARENA_URL)],
    latencyMs: 720, throughputTps: 75, rating: 4.6,
    blurb: "Sparse-attention V3 refresh — cheaper long-context with toggleable thinking.",
    routes: [
      { provider: "openrouter", model: "deepseek/deepseek-v3.2" },
      { provider: "local", model: "deepseek-v3.2" },
    ],
    tags: ["open", "moe", "reasoning", "value"],
  },
  {
    id: "deepseek-v3-1-terminus",
    name: "DeepSeek V3.1 Terminus",
    provider: "DeepSeek",
    family: "DeepSeek V3",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-09-22",
    contextWindow: 163840,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.27, outputPerM: 0.95, cachedInputPerM: 0.07, effectiveFrom: "2025-09-22" },
    benchmarks: [b("gpqa", 74.9, OR, OR_URL), b("aime", 88.4, "DeepSeek", "https://deepseek.com")],
    latencyMs: 760, throughputTps: 62, rating: 4.6,
    blurb: "Hybrid instruct+reasoning 685B MoE — frontier open quality.",
    routes: [
      { provider: "openrouter", model: "deepseek/deepseek-v3.1-terminus" },
      { provider: "local", model: "deepseek-v3.1" },
    ],
    tags: ["open", "moe", "reasoning"],
  },
  {
    id: "deepseek-r1-0528",
    name: "DeepSeek R1 (0528)",
    provider: "DeepSeek",
    family: "DeepSeek R1",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-05-28",
    contextWindow: 163840,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.5, outputPerM: 2.15, cachedInputPerM: 0.14, effectiveFrom: "2025-05-28" },
    benchmarks: [
      b("gpqa", 81.0, "DeepSeek", "https://deepseek.com"),
      b("aime", 87.5, "DeepSeek", "https://deepseek.com"),
      b("arena", 1410, ARENA, ARENA_URL),
    ],
    latencyMs: 5200, throughputTps: 58, rating: 4.7,
    blurb: "The upgraded open reasoning model with visible chain-of-thought.",
    routes: [
      { provider: "openrouter", model: "deepseek/deepseek-r1-0528" },
      { provider: "local", model: "deepseek-r1" },
    ],
    tags: ["reasoning", "open", "math"],
  },
  {
    id: "deepseek-r1-distill-llama-70b",
    name: "DeepSeek R1 Distill 70B",
    provider: "DeepSeek",
    family: "DeepSeek R1",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-01-20",
    contextWindow: 128000,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: false, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.8, outputPerM: 0.8, effectiveFrom: "2025-01-20" },
    benchmarks: [b("aime", 70.0, "DeepSeek", "https://deepseek.com"), b("gpqa", 65.2, "DeepSeek", "https://deepseek.com")],
    latencyMs: 1800, throughputTps: 85, rating: 4.3,
    blurb: "R1 reasoning distilled into a Llama 70B — cheaper to run with strong math.",
    routes: [
      { provider: "openrouter", model: "deepseek/deepseek-r1-distill-llama-70b" },
      { provider: "local", model: "deepseek-r1:70b" },
    ],
    tags: ["reasoning", "open", "distill"],
  },

  // ===== Alibaba — Qwen ====================================================
  {
    id: "qwen3-7-max",
    name: "Qwen3.7 Max",
    provider: "Alibaba",
    family: "Qwen3 Max",
    license: "proprietary",
    access: "byok",
    trending: true,
    status: "ga",
    releaseDate: "2026-05-10",
    addedAt: ADDED,
    contextWindow: 1000000,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 1.25, outputPerM: 3.75, effectiveFrom: "2026-05-10" },
    benchmarks: [
      b("gpqa", 86.0, OR, OR_URL),
      b("swebench", 75.0, OR, OR_URL),
      b("arena", 1465, ARENA, ARENA_URL),
    ],
    latencyMs: 800, throughputTps: 80, rating: 4.7,
    blurb: "Alibaba's frontier closed Qwen — top-tier reasoning and agentic coding.",
    routes: [{ provider: "openrouter", model: "qwen/qwen3.7-max" }],
    tags: ["reasoning", "coding", "long-context"],
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    provider: "Alibaba",
    family: "Qwen3 Max",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-09-24",
    contextWindow: 262144,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0.78, outputPerM: 3.9, effectiveFrom: "2025-09-24" },
    benchmarks: [b("gpqa", 82.0, OR, OR_URL), b("arena", 1430, ARENA, ARENA_URL)],
    latencyMs: 820, throughputTps: 78, rating: 4.6,
    blurb: "Trillion-parameter flagship Qwen with strong agentic ability.",
    routes: [{ provider: "openrouter", model: "qwen/qwen3-max" }],
    tags: ["reasoning", "coding"],
  },
  {
    id: "qwen3-235b",
    name: "Qwen3 235B A22B",
    provider: "Alibaba",
    family: "Qwen3",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2025-07-22",
    contextWindow: 262144,
    maxOutput: 16384,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.09, outputPerM: 0.1, effectiveFrom: "2025-07-22" },
    benchmarks: [
      b("gpqa", 79.0, "Alibaba", "https://qwenlm.github.io"),
      b("aime", 90.0, "Alibaba", "https://qwenlm.github.io"),
      b("arena", 1400, ARENA, ARENA_URL),
    ],
    latencyMs: 700, throughputTps: 80, rating: 4.6,
    blurb: "Qwen's flagship open MoE with hybrid thinking — frontier-class open reasoning.",
    routes: [
      { provider: "openrouter", model: "qwen/qwen3-235b-a22b-2507" },
      { provider: "local", model: "qwen3:235b" },
    ],
    tags: ["open", "moe", "reasoning"],
  },
  {
    id: "qwen3-coder",
    name: "Qwen3 Coder",
    provider: "Alibaba",
    family: "Qwen3 Coder",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2025-07-23",
    contextWindow: 1048576,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.22, outputPerM: 1.8, effectiveFrom: "2025-07-23" },
    benchmarks: [b("swebench", 69.6, "Alibaba", "https://qwenlm.github.io"), b("humaneval", 94.0, AA, AA_URL)],
    latencyMs: 600, throughputTps: 90, rating: 4.6,
    blurb: "Open agentic coding MoE with a 1M context — rivals closed coding models.",
    routes: [
      { provider: "openrouter", model: "qwen/qwen3-coder" },
      { provider: "local", model: "qwen3-coder" },
    ],
    tags: ["coding", "open", "agentic", "long-context"],
  },
  {
    id: "qwen3-next-80b",
    name: "Qwen3 Next 80B A3B",
    provider: "Alibaba",
    family: "Qwen3 Next",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-09-12",
    contextWindow: 262144,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.09, outputPerM: 1.1, effectiveFrom: "2025-09-12" },
    benchmarks: [b("gpqa", 72.0, "Alibaba", "https://qwenlm.github.io"), b("aime", 84.0, "Alibaba", "https://qwenlm.github.io")],
    latencyMs: 420, throughputTps: 130, rating: 4.4,
    blurb: "Ultra-sparse 80B MoE (3B active) — fast, cheap open reasoning.",
    routes: [
      { provider: "nvidia", model: "qwen/qwen3-next-80b-a3b-instruct" },
      { provider: "openrouter", model: "qwen/qwen3-next-80b-a3b-instruct" },
      { provider: "local", model: "qwen3-next:80b" },
    ],
    tags: ["open", "moe", "reasoning", "cheap"],
  },
  {
    id: "qwen3-vl-235b",
    name: "Qwen3-VL 235B",
    provider: "Alibaba",
    family: "Qwen3 VL",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-10-01",
    contextWindow: 262144,
    maxOutput: 16384,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.2, outputPerM: 0.88, effectiveFrom: "2025-10-01" },
    benchmarks: [b("mmmu", 78.0, "Alibaba", "https://qwenlm.github.io")],
    latencyMs: 700, throughputTps: 70, rating: 4.5,
    blurb: "Leading open vision-language MoE — strong document and UI understanding.",
    routes: [
      { provider: "openrouter", model: "qwen/qwen3-vl-235b-a22b-instruct" },
      { provider: "local", model: "qwen3-vl:235b" },
    ],
    tags: ["open", "vision", "moe"],
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    provider: "Alibaba",
    family: "Qwen3",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-04-29",
    contextWindow: 131072,
    maxOutput: 16384,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.08, outputPerM: 0.28, effectiveFrom: "2025-04-29" },
    benchmarks: [b("gpqa", 65.8, "Alibaba", "https://qwenlm.github.io"), b("aime", 81.4, "Alibaba", "https://qwenlm.github.io")],
    latencyMs: 520, throughputTps: 100, rating: 4.4,
    blurb: "Dense 32B with toggleable thinking — excellent reasoning per parameter.",
    routes: [
      { provider: "groq", model: "qwen/qwen3-32b" },
      { provider: "openrouter", model: "qwen/qwen3-32b" },
      { provider: "local", model: "qwen3:32b" },
    ],
    tags: ["open", "reasoning"],
  },
  {
    id: "qwen3-6-27b",
    name: "Qwen3.6 27B",
    provider: "Alibaba",
    family: "Qwen3.6",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2026-05-06",
    addedAt: ADDED,
    contextWindow: 131072,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: false, reasoning: true, caching: false },
    pricing: { inputPerM: 0.6, outputPerM: 3, effectiveFrom: "2026-05-06" },
    benchmarks: [b("gpqa", 70.0, "Alibaba", "https://qwenlm.github.io")],
    latencyMs: 380, throughputTps: 150, rating: 4.4,
    blurb: "Latest mid-size Qwen — vision plus thinking at LPU speed on Groq.",
    routes: [{ provider: "groq", model: "qwen/qwen3.6-27b" }],
    tags: ["open", "reasoning", "multimodal"],
  },
  {
    id: "qwen-2-5-coder-32b",
    name: "Qwen 2.5 Coder 32B",
    provider: "Alibaba",
    family: "Qwen 2.5 Coder",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-11-12",
    contextWindow: 128000,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.66, outputPerM: 1, effectiveFrom: "2024-11-12" },
    benchmarks: [b("humaneval", 92.7, AA, AA_URL), b("swebench", 40.2, AA, AA_URL)],
    latencyMs: 360, throughputTps: 110, rating: 4.4,
    blurb: "Open coding specialist matching far larger models on code generation.",
    routes: [
      { provider: "openrouter", model: "qwen/qwen-2.5-coder-32b-instruct" },
      { provider: "local", model: "qwen2.5-coder:32b" },
    ],
    tags: ["coding", "open"],
  },
  {
    id: "qwen-2-5-72b",
    name: "Qwen 2.5 72B",
    provider: "Alibaba",
    family: "Qwen 2.5",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-09-19",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.36, outputPerM: 0.4, effectiveFrom: "2024-10-01" },
    benchmarks: [b("humaneval", 86.6, AA, AA_URL), b("mmlu", 85.3, AA, AA_URL), b("arena", 1257, ARENA, ARENA_URL)],
    latencyMs: 520, throughputTps: 90, rating: 4.3,
    blurb: "Excellent multilingual open model with strong math and coding.",
    routes: [
      { provider: "openrouter", model: "qwen/qwen-2.5-72b-instruct" },
      { provider: "local", model: "qwen2.5:72b" },
    ],
    tags: ["open", "multilingual"],
  },

  // ===== Moonshot AI (open) ================================================
  {
    id: "kimi-k2-7-code",
    name: "Kimi K2.7 Code",
    provider: "Moonshot AI",
    family: "Kimi",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2026-05-18",
    addedAt: ADDED,
    contextWindow: 262144,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.74, outputPerM: 3.5, effectiveFrom: "2026-05-18" },
    benchmarks: [b("swebench", 73.0, "Moonshot AI", "https://moonshot.ai"), b("arena", 1430, ARENA, ARENA_URL)],
    latencyMs: 720, throughputTps: 60, rating: 4.7,
    blurb: "Open agentic coding MoE from Moonshot — a standout for autonomous engineering.",
    routes: [
      { provider: "openrouter", model: "moonshotai/kimi-k2.7-code" },
      { provider: "local", model: "kimi-k2.7" },
    ],
    tags: ["open", "moe", "coding", "agentic"],
  },
  {
    id: "kimi-k2-6",
    name: "Kimi K2.6",
    provider: "Moonshot AI",
    family: "Kimi",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2026-03-30",
    contextWindow: 262144,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.55, outputPerM: 3.2, effectiveFrom: "2026-03-30" },
    benchmarks: [b("swebench", 70.0, "Moonshot AI", "https://moonshot.ai"), b("arena", 1410, ARENA, ARENA_URL)],
    latencyMs: 720, throughputTps: 62, rating: 4.6,
    blurb: "Multimodal Kimi MoE with strong agentic and long-context ability.",
    routes: [
      { provider: "nvidia", model: "moonshotai/kimi-k2.6" },
      { provider: "openrouter", model: "moonshotai/kimi-k2.6" },
      { provider: "local", model: "kimi-k2.6" },
    ],
    tags: ["open", "moe", "agentic", "vision"],
  },
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    provider: "Moonshot AI",
    family: "Kimi",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-11-06",
    contextWindow: 262144,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.6, outputPerM: 2.5, effectiveFrom: "2025-11-06" },
    benchmarks: [b("aime", 89.0, "Moonshot AI", "https://moonshot.ai"), b("gpqa", 78.0, "Moonshot AI", "https://moonshot.ai")],
    latencyMs: 3200, throughputTps: 58, rating: 4.6,
    blurb: "Reasoning-tuned Kimi MoE with visible deliberation.",
    routes: [
      { provider: "openrouter", model: "moonshotai/kimi-k2-thinking" },
      { provider: "local", model: "kimi-k2-thinking" },
    ],
    tags: ["open", "moe", "reasoning"],
  },

  // ===== Zhipu / Z-AI (open) ===============================================
  {
    id: "glm-5-1",
    name: "GLM-5.1",
    provider: "Zhipu AI",
    family: "GLM-5",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2026-05-30",
    addedAt: ADDED,
    contextWindow: 200000,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.5, outputPerM: 2, effectiveFrom: "2026-05-30" },
    benchmarks: [b("gpqa", 82.0, NV, NV_URL), b("swebench", 70.0, NV, NV_URL), b("arena", 1440, ARENA, ARENA_URL)],
    latencyMs: 720, throughputTps: 80, rating: 4.7,
    blurb: "Zhipu's latest open flagship — frontier agentic + reasoning, hosted on NIM.",
    routes: [
      { provider: "nvidia", model: "z-ai/glm-5.1" },
      { provider: "local", model: "glm-5.1" },
    ],
    tags: ["open", "moe", "reasoning", "agentic"],
  },
  {
    id: "glm-4-6",
    name: "GLM-4.6",
    provider: "Zhipu AI",
    family: "GLM-4",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-09-30",
    contextWindow: 202752,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.43, outputPerM: 1.74, effectiveFrom: "2025-09-30" },
    benchmarks: [b("gpqa", 79.0, OR, OR_URL), b("swebench", 68.0, OR, OR_URL), b("arena", 1420, ARENA, ARENA_URL)],
    latencyMs: 720, throughputTps: 80, rating: 4.6,
    blurb: "Open MoE with hybrid thinking — agentic, reasoning, and coding in one.",
    routes: [
      { provider: "openrouter", model: "z-ai/glm-4.6" },
      { provider: "local", model: "glm-4.6" },
    ],
    tags: ["open", "moe", "reasoning", "agentic"],
  },
  {
    id: "glm-4-6v",
    name: "GLM-4.6V",
    provider: "Zhipu AI",
    family: "GLM-4",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-10-20",
    contextWindow: 131072,
    maxOutput: 16384,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.3, outputPerM: 0.9, effectiveFrom: "2025-10-20" },
    benchmarks: [b("mmmu", 74.0, OR, OR_URL)],
    latencyMs: 640, throughputTps: 75, rating: 4.4,
    blurb: "Open vision-language GLM with strong chart and document understanding.",
    routes: [
      { provider: "openrouter", model: "z-ai/glm-4.6v" },
      { provider: "local", model: "glm-4.6v" },
    ],
    tags: ["open", "vision"],
  },
  {
    id: "glm-4-5-air",
    name: "GLM-4.5 Air",
    provider: "Zhipu AI",
    family: "GLM-4",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-07-28",
    contextWindow: 131072,
    maxOutput: 16384,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.13, outputPerM: 0.85, effectiveFrom: "2025-07-28" },
    benchmarks: [b("gpqa", 72.0, OR, OR_URL)],
    latencyMs: 480, throughputTps: 110, rating: 4.3,
    blurb: "Lightweight GLM-4.5 MoE — cheap, fast open reasoning.",
    routes: [
      { provider: "openrouter", model: "z-ai/glm-4.5-air" },
      { provider: "local", model: "glm-4.5-air" },
    ],
    tags: ["open", "moe", "cheap"],
  },

  // ===== MiniMax (open) ====================================================
  {
    id: "minimax-m3",
    name: "MiniMax M3",
    provider: "MiniMax",
    family: "MiniMax M",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2026-04-12",
    addedAt: ADDED,
    contextWindow: 1048576,
    maxOutput: 32768,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.3, outputPerM: 1.2, effectiveFrom: "2026-04-12" },
    benchmarks: [b("gpqa", 78.0, NV, NV_URL), b("arena", 1420, ARENA, ARENA_URL)],
    latencyMs: 700, throughputTps: 75, rating: 4.6,
    blurb: "MiniMax's open 1M-context multimodal reasoning MoE, hosted on NIM.",
    routes: [
      { provider: "nvidia", model: "minimaxai/minimax-m3" },
      { provider: "openrouter", model: "minimax/minimax-m3" },
      { provider: "local", model: "minimax-m3" },
    ],
    tags: ["open", "moe", "reasoning", "long-context"],
  },
  {
    id: "minimax-m2-7",
    name: "MiniMax M2.7",
    provider: "MiniMax",
    family: "MiniMax M",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2026-02-08",
    contextWindow: 204800,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.255, outputPerM: 1, effectiveFrom: "2026-02-08" },
    benchmarks: [b("gpqa", 74.0, OR, OR_URL)],
    latencyMs: 680, throughputTps: 80, rating: 4.5,
    blurb: "Agentic open reasoning MoE tuned for tool use and coding.",
    routes: [
      { provider: "nvidia", model: "minimaxai/minimax-m2.7" },
      { provider: "openrouter", model: "minimax/minimax-m2" },
      { provider: "local", model: "minimax-m2" },
    ],
    tags: ["open", "moe", "reasoning", "agentic"],
  },

  // ===== Groq — Compound (agentic systems) =================================
  {
    id: "groq-compound",
    name: "Groq Compound",
    provider: "Groq",
    family: "Compound",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2025-09-04",
    addedAt: ADDED,
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: false, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.35, outputPerM: 0.6, effectiveFrom: "2025-09-04" },
    benchmarks: [],
    latencyMs: 350, throughputTps: 350, rating: 4.2,
    blurb: "Groq's agentic system — built-in web search and code execution at LPU speed.",
    routes: [{ provider: "groq", model: "groq/compound" }],
    tags: ["agentic", "fast", "search"],
  },
  {
    id: "groq-compound-mini",
    name: "Groq Compound Mini",
    provider: "Groq",
    family: "Compound",
    license: "proprietary",
    access: "free",
    status: "ga",
    releaseDate: "2025-09-04",
    addedAt: ADDED,
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: false, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.2, outputPerM: 0.4, effectiveFrom: "2025-09-04" },
    benchmarks: [],
    latencyMs: 250, throughputTps: 400, rating: 4.0,
    blurb: "Lighter Compound variant for low-latency agentic lookups.",
    routes: [{ provider: "groq", model: "groq/compound-mini" }],
    tags: ["agentic", "fast", "cheap"],
  },

  // ===== NVIDIA — Nemotron (open) ==========================================
  {
    id: "nemotron-3-ultra-550b",
    name: "Nemotron 3 Ultra 550B",
    provider: "NVIDIA",
    family: "Nemotron 3",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2026-03-18",
    addedAt: ADDED,
    contextWindow: 1000000,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.5, outputPerM: 2.2, effectiveFrom: "2026-03-18" },
    benchmarks: [b("gpqa", 82.0, NV, NV_URL), b("aime", 92.0, NV, NV_URL), b("arena", 1445, ARENA, ARENA_URL)],
    latencyMs: 1600, throughputTps: 70, rating: 4.7,
    blurb: "NVIDIA's flagship open reasoning MoE — frontier accuracy, 1M context.",
    routes: [
      { provider: "nvidia", model: "nvidia/nemotron-3-ultra-550b-a55b" },
      { provider: "openrouter", model: "nvidia/nemotron-3-ultra-550b-a55b" },
      { provider: "local", model: "nemotron-3-ultra" },
    ],
    tags: ["open", "moe", "reasoning", "aligned"],
  },
  {
    id: "nemotron-3-super-120b",
    name: "Nemotron 3 Super 120B",
    provider: "NVIDIA",
    family: "Nemotron 3",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2026-03-18",
    contextWindow: 1000000,
    maxOutput: 32768,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.085, outputPerM: 0.4, effectiveFrom: "2026-03-18" },
    benchmarks: [b("gpqa", 76.0, NV, NV_URL), b("aime", 85.0, NV, NV_URL)],
    latencyMs: 900, throughputTps: 95, rating: 4.5,
    blurb: "Efficient open reasoning MoE tuned for accuracy-per-GPU.",
    routes: [
      { provider: "nvidia", model: "nvidia/nemotron-3-super-120b-a12b" },
      { provider: "openrouter", model: "nvidia/nemotron-3-super-120b-a12b" },
      { provider: "local", model: "nemotron-3-super" },
    ],
    tags: ["open", "moe", "reasoning", "value"],
  },
  {
    id: "nemotron-super-49b-1-5",
    name: "Llama Nemotron Super 49B v1.5",
    provider: "NVIDIA",
    family: "Nemotron",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-07-10",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.4, outputPerM: 0.4, effectiveFrom: "2025-07-10" },
    benchmarks: [b("gpqa", 68.0, NV, NV_URL), b("aime", 75.0, NV, NV_URL)],
    latencyMs: 1600, throughputTps: 90, rating: 4.3,
    blurb: "NAS-distilled Llama reasoning model tuned for throughput.",
    routes: [
      { provider: "nvidia", model: "nvidia/llama-3.3-nemotron-super-49b-v1.5" },
      { provider: "openrouter", model: "nvidia/llama-3.3-nemotron-super-49b-v1.5" },
      { provider: "local", model: "nemotron-super:49b" },
    ],
    tags: ["open", "reasoning"],
  },
  {
    id: "nemotron-nano-9b-v2",
    name: "Nemotron Nano 9B v2",
    provider: "NVIDIA",
    family: "Nemotron",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-08-20",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.03, outputPerM: 0.06, effectiveFrom: "2025-08-20" },
    benchmarks: [b("gpqa", 56.0, NV, NV_URL), b("aime", 62.0, NV, NV_URL)],
    latencyMs: 240, throughputTps: 175, rating: 4.0,
    blurb: "Tiny open reasoning model for the edge — strong STEM on a single GPU.",
    routes: [
      { provider: "nvidia", model: "nvidia/nvidia-nemotron-nano-9b-v2" },
      { provider: "local", model: "nemotron-nano:9b" },
    ],
    tags: ["open", "reasoning", "cheap", "edge"],
  },
  {
    id: "nemotron-70b",
    name: "Llama 3.1 Nemotron 70B",
    provider: "NVIDIA",
    family: "Nemotron",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-10-15",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.2, outputPerM: 0.2, effectiveFrom: "2024-10-15" },
    benchmarks: [b("mmlu", 85.5, AA, AA_URL), b("arena", 1269, ARENA, ARENA_URL)],
    latencyMs: 500, throughputTps: 95, rating: 4.3,
    blurb: "RLHF-tuned Llama that tops several alignment & helpfulness benchmarks.",
    routes: [
      { provider: "nvidia", model: "nvidia/llama-3.1-nemotron-70b-instruct" },
      { provider: "local", model: "nemotron" },
    ],
    tags: ["open", "aligned"],
  },

  // ===== Mistral ===========================================================
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    provider: "Mistral",
    family: "Mistral Large",
    license: "open",
    access: "free",
    trending: true,
    status: "ga",
    releaseDate: "2025-12-04",
    addedAt: ADDED,
    contextWindow: 262144,
    maxOutput: 16384,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.5, outputPerM: 1.5, effectiveFrom: "2025-12-04" },
    benchmarks: [b("gpqa", 75.0, NV, NV_URL), b("humaneval", 92.0, AA, AA_URL), b("arena", 1400, ARENA, ARENA_URL)],
    latencyMs: 560, throughputTps: 85, rating: 4.6,
    blurb: "Mistral's open 675B flagship — strong multilingual reasoning and coding.",
    routes: [
      { provider: "nvidia", model: "mistralai/mistral-large-3-675b-instruct-2512" },
      { provider: "openrouter", model: "mistralai/mistral-large-2512" },
      { provider: "local", model: "mistral-large-3" },
    ],
    tags: ["open", "multilingual", "reasoning"],
  },
  {
    id: "mistral-medium-3-1",
    name: "Mistral Medium 3.1",
    provider: "Mistral",
    family: "Mistral Medium",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-08-13",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.4, outputPerM: 2, effectiveFrom: "2025-08-13" },
    benchmarks: [b("gpqa", 62.0, AA, AA_URL), b("humaneval", 92.0, AA, AA_URL)],
    latencyMs: 520, throughputTps: 90, rating: 4.4,
    blurb: "Frontier-class quality at low cost — Mistral's efficient enterprise model.",
    routes: [{ provider: "openrouter", model: "mistralai/mistral-medium-3.1" }],
    tags: ["coding", "value", "multimodal"],
  },
  {
    id: "mistral-small-3-2",
    name: "Mistral Small 3.2 24B",
    provider: "Mistral",
    family: "Mistral Small",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-06-20",
    contextWindow: 128000,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.075, outputPerM: 0.2, effectiveFrom: "2025-06-20" },
    benchmarks: [b("gpqa", 46.0, AA, AA_URL), b("humaneval", 88.0, AA, AA_URL)],
    latencyMs: 300, throughputTps: 150, rating: 4.3,
    blurb: "Apache-2.0 24B with vision and a 128K context — fast, cheap, capable.",
    routes: [
      { provider: "openrouter", model: "mistralai/mistral-small-3.2-24b-instruct" },
      { provider: "local", model: "mistral-small3.2" },
    ],
    tags: ["open", "multimodal", "fast"],
  },
  {
    id: "codestral-22b",
    name: "Codestral 22B",
    provider: "Mistral",
    family: "Codestral",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-01-13",
    contextWindow: 32768,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.3, outputPerM: 0.9, effectiveFrom: "2025-01-13" },
    benchmarks: [b("humaneval", 86.6, "Mistral", "https://mistral.ai")],
    latencyMs: 280, throughputTps: 130, rating: 4.2,
    blurb: "Mistral's open code model with fast fill-in-the-middle completion.",
    routes: [
      { provider: "nvidia", model: "mistralai/codestral-22b-instruct-v0.1" },
      { provider: "local", model: "codestral" },
    ],
    tags: ["coding", "open"],
  },
  {
    id: "mistral-nemo",
    name: "Mistral Nemo 12B",
    provider: "Mistral",
    family: "Nemo",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-07-18",
    contextWindow: 131072,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.02, outputPerM: 0.03, effectiveFrom: "2024-09-01" },
    benchmarks: [b("mmlu", 68.0, AA, AA_URL)],
    latencyMs: 300, throughputTps: 140, rating: 3.9,
    blurb: "Compact 12B open model with a long context — a cheap self-host baseline.",
    routes: [
      { provider: "nvidia", model: "nv-mistralai/mistral-nemo-12b-instruct" },
      { provider: "openrouter", model: "mistralai/mistral-nemo" },
      { provider: "local", model: "mistral-nemo" },
    ],
    tags: ["cheap", "open"],
  },
  {
    id: "mixtral-8x22b",
    name: "Mixtral 8x22B",
    provider: "Mistral",
    family: "Mixtral",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-04-17",
    contextWindow: 65536,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 2, outputPerM: 6, effectiveFrom: "2024-09-01" },
    benchmarks: [b("mmlu", 77.8, AA, AA_URL), b("arena", 1148, ARENA, ARENA_URL)],
    latencyMs: 480, throughputTps: 88, rating: 4.0,
    blurb: "Sparse MoE open model — efficient inference with solid general ability.",
    routes: [
      { provider: "nvidia", model: "mistralai/mixtral-8x22b-v0.1" },
      { provider: "openrouter", model: "mistralai/mixtral-8x22b-instruct" },
      { provider: "local", model: "mixtral:8x22b" },
    ],
    tags: ["moe", "open"],
  },

  // ===== Cohere / Perplexity / Amazon / Microsoft / others =================
  {
    id: "command-a",
    name: "Command A",
    provider: "Cohere",
    family: "Command",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-03-13",
    contextWindow: 256000,
    maxOutput: 8192,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 2.5, outputPerM: 10, effectiveFrom: "2025-03-13" },
    benchmarks: [b("mmlu", 85.5, AA, AA_URL), b("arena", 1305, ARENA, ARENA_URL)],
    latencyMs: 480, throughputTps: 156, rating: 4.3,
    blurb: "Cohere's enterprise flagship — agentic, RAG-tuned, 256K context, open weights.",
    routes: [
      { provider: "openrouter", model: "cohere/command-a" },
      { provider: "local", model: "command-a" },
    ],
    tags: ["rag", "open", "tools", "long-context"],
  },
  {
    id: "sonar-pro",
    name: "Perplexity Sonar Pro",
    provider: "Perplexity",
    family: "Sonar",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-01-21",
    contextWindow: 200000,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 3, outputPerM: 15, effectiveFrom: "2025-01-21" },
    benchmarks: [b("mmlu", 84.0, "Perplexity", "https://perplexity.ai")],
    latencyMs: 1400, throughputTps: 70, rating: 4.3,
    blurb: "Search-grounded model that answers with live web citations.",
    routes: [{ provider: "openrouter", model: "perplexity/sonar-pro" }],
    tags: ["search", "realtime", "rag"],
  },
  {
    id: "sonar-reasoning-pro",
    name: "Perplexity Sonar Reasoning Pro",
    provider: "Perplexity",
    family: "Sonar",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2025-03-07",
    contextWindow: 128000,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 2, outputPerM: 8, effectiveFrom: "2025-03-07" },
    benchmarks: [b("gpqa", 70.0, "Perplexity", "https://perplexity.ai")],
    latencyMs: 3000, throughputTps: 65, rating: 4.3,
    blurb: "Web-grounded reasoning with citations — research that shows its work.",
    routes: [{ provider: "openrouter", model: "perplexity/sonar-reasoning-pro" }],
    tags: ["search", "reasoning", "rag"],
  },
  {
    id: "nova-pro",
    name: "Amazon Nova Pro",
    provider: "Amazon",
    family: "Nova",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2024-12-03",
    contextWindow: 300000,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.8, outputPerM: 3.2, effectiveFrom: "2024-12-03" },
    benchmarks: [b("mmlu", 85.9, "Amazon", "https://aws.amazon.com"), b("mmmu", 61.6, "Amazon", "https://aws.amazon.com")],
    latencyMs: 520, throughputTps: 100, rating: 4.2,
    blurb: "Amazon's multimodal workhorse with a 300K context and strong value on Bedrock.",
    routes: [{ provider: "openrouter", model: "amazon/nova-pro-v1" }],
    tags: ["multimodal", "long-context", "value"],
  },
  {
    id: "nova-lite",
    name: "Amazon Nova Lite",
    provider: "Amazon",
    family: "Nova",
    license: "proprietary",
    access: "byok",
    status: "ga",
    releaseDate: "2024-12-03",
    contextWindow: 300000,
    maxOutput: 8192,
    modalities: ["text", "vision"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.06, outputPerM: 0.24, effectiveFrom: "2024-12-03" },
    benchmarks: [b("mmlu", 80.5, "Amazon", "https://aws.amazon.com")],
    latencyMs: 300, throughputTps: 150, rating: 4.0,
    blurb: "Very cheap multimodal model with a 300K context — high-volume documents.",
    routes: [{ provider: "openrouter", model: "amazon/nova-lite-v1" }],
    tags: ["cheap", "multimodal", "long-context"],
  },
  {
    id: "phi-4-multimodal",
    name: "Phi-4 Multimodal",
    provider: "Microsoft",
    family: "Phi",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2025-02-26",
    contextWindow: 131072,
    maxOutput: 4096,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.07, outputPerM: 0.14, effectiveFrom: "2025-02-26" },
    benchmarks: [b("mmlu", 80.0, NV, NV_URL), b("mmmu", 55.0, NV, NV_URL)],
    latencyMs: 280, throughputTps: 130, rating: 4.1,
    blurb: "Small open model with vision and audio — remarkable capability per parameter.",
    routes: [
      { provider: "nvidia", model: "microsoft/phi-4-multimodal-instruct" },
      { provider: "local", model: "phi4-multimodal" },
    ],
    tags: ["small", "open", "multimodal"],
  },
  {
    id: "phi-4",
    name: "Phi-4 14B",
    provider: "Microsoft",
    family: "Phi",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-12-12",
    contextWindow: 16384,
    maxOutput: 4096,
    modalities: ["text"],
    capabilities: { toolUse: false, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.07, outputPerM: 0.14, effectiveFrom: "2024-12-12" },
    benchmarks: [b("gpqa", 56.1, AA, AA_URL), b("math", 80.4, AA, AA_URL)],
    latencyMs: 280, throughputTps: 130, rating: 4.1,
    blurb: "Small open model trained on curated synthetic data — strong reasoning per parameter.",
    routes: [
      { provider: "openrouter", model: "microsoft/phi-4" },
      { provider: "local", model: "phi4" },
    ],
    tags: ["small", "open", "reasoning"],
  },
  {
    id: "step-3-7-flash",
    name: "Step 3.7 Flash",
    provider: "StepFun",
    family: "Step",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2026-04-01",
    contextWindow: 131072,
    maxOutput: 16384,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0.1, outputPerM: 0.4, effectiveFrom: "2026-04-01" },
    benchmarks: [b("gpqa", 70.0, NV, NV_URL)],
    latencyMs: 420, throughputTps: 120, rating: 4.3,
    blurb: "StepFun's fast open reasoning model, hosted on NIM.",
    routes: [
      { provider: "nvidia", model: "stepfun-ai/step-3.7-flash" },
      { provider: "local", model: "step-3.7-flash" },
    ],
    tags: ["open", "reasoning", "fast"],
  },
  {
    id: "jamba-1-5-large",
    name: "Jamba 1.5 Large",
    provider: "AI21",
    family: "Jamba",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-08-22",
    contextWindow: 256000,
    maxOutput: 4096,
    modalities: ["text"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 2, outputPerM: 8, effectiveFrom: "2024-09-01" },
    benchmarks: [b("mmlu", 81.2, AA, AA_URL)],
    latencyMs: 620, throughputTps: 80, rating: 4.0,
    blurb: "Hybrid SSM-Transformer (Mamba) open model with an efficient 256K context.",
    routes: [
      { provider: "nvidia", model: "ai21labs/jamba-1.5-large-instruct" },
      { provider: "openrouter", model: "ai21/jamba-1.5-large" },
      { provider: "local", model: "jamba:large" },
    ],
    tags: ["open", "long-context", "mamba"],
  },
  {
    id: "dbrx",
    name: "DBRX Instruct",
    provider: "Databricks",
    family: "DBRX",
    license: "open",
    access: "free",
    status: "ga",
    releaseDate: "2024-03-27",
    contextWindow: 32768,
    maxOutput: 4096,
    modalities: ["text"],
    capabilities: { toolUse: false, structuredOutput: true, reasoning: false, caching: false },
    pricing: { inputPerM: 0.6, outputPerM: 0.6, effectiveFrom: "2024-09-01" },
    benchmarks: [b("mmlu", 73.7, AA, AA_URL)],
    latencyMs: 460, throughputTps: 90, rating: 3.8,
    blurb: "Databricks' 132B open MoE — a strong enterprise base for fine-tuning.",
    routes: [
      { provider: "nvidia", model: "databricks/dbrx-instruct" },
      { provider: "local", model: "dbrx" },
    ],
    tags: ["open", "moe", "enterprise"],
  },

  // ===== Upcoming ==========================================================
  {
    id: "gemini-4-pro",
    name: "Gemini 4 Pro",
    provider: "Google",
    family: "Gemini 4",
    license: "proprietary",
    access: "byok",
    status: "upcoming",
    releaseDate: "2026-09-01",
    contextWindow: 2097152,
    maxOutput: 65536,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: true },
    pricing: { inputPerM: 0, outputPerM: 0, effectiveFrom: "2026-09-01" },
    benchmarks: [],
    rating: undefined,
    blurb: "Google's announced next-gen flagship — tracked on the Upcoming board.",
    routes: [],
    tags: ["upcoming"],
  },
  {
    id: "llama-5",
    name: "Llama 5",
    provider: "Meta",
    family: "Llama 5",
    license: "open",
    access: "free",
    status: "upcoming",
    releaseDate: "2026-10-01",
    contextWindow: 10000000,
    maxOutput: 32768,
    modalities: ["text", "vision", "audio"],
    capabilities: { toolUse: true, structuredOutput: true, reasoning: true, caching: false },
    pricing: { inputPerM: 0, outputPerM: 0, effectiveFrom: "2026-10-01" },
    benchmarks: [],
    rating: undefined,
    blurb: "Meta's next open-weight generation — expected natively omni-modal.",
    routes: [],
    tags: ["upcoming", "open"],
  },
];
